/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Cart: typeof import('./src/components/Cart/Cart.vue')['default']
    Details: typeof import('./src/components/Details/Details.vue')['default']
    FeaturedProducts: typeof import('./src/components/Home/FeaturedProducts.vue')['default']
    FilteredProducts: typeof import('./src/components/Filters/FilteredProducts.vue')['default']
    Footer: typeof import('./src/components/Footer/Footer.vue')['default']
    Header: typeof import('./src/components/Header/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HomePage: typeof import('./src/components/Home/HomePage.vue')['default']
    LeatestPage: typeof import('./src/components/Home/LeatestPage.vue')['default']
    MainPage: typeof import('./src/components/Home/MainPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RowFilterPage: typeof import('./src/components/Filters/RowFilterPage.vue')['default']
  }
}
